version: '3.2.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
- cmd: git config --global core.autocrlf true
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- cmd: dotnet pack -c Release -o artifacts
  
artifacts:
- path: '**\*.nupkg'
  name: AutoTesting  

clone_depth: 1

test: off
deploy:
  provider: NuGet
  server:
  api_key:
    secure: 0UpJx5Ly4LHMXQsCW9P5q2GtDk66piKIwQaBbpiQYt9exz1h1RAMjvo+AUOkIfUl